### ISSUE TITLE
app manifest

### ISSUE THREAD

**Issue by artemave** [featurist/pr-apps#1]
Something like this:

```yaml
env:
  FOO: bar
  DEBUG: true
resources:
  - redis
routes:
  api-web:
    subdomain: api
scale:
  web: 2
  api-web: 1
```
